// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MSIT64Ajax.Models;

public partial class Category
{
    public int CategoryId { get; set; }
    public string CategoryName { get; set; }
}